In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import re

In [2]:
dc = pd.read_csv('raw_dataset/olist_order_payments_dataset.csv') 
dc.info() 
dc.head()

<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [3]:
dc.columns.is_unique #Check data duplikat di setiap kolom (output: True)

True

In [4]:
#Check jumlah missing value di setiap kolom  
print('order_id: ', dc['order_id'].isna().sum())
print('payment_sequential: ', dc['payment_sequential'].isna().sum())
print('payment_type: ', dc['payment_type'].isna().sum())
print('payment_installments: ', dc['payment_installments'].isna().sum()) 
print('payment_value: ', dc['payment_value'].isna().sum())

order_id:  0
payment_sequential:  0
payment_type:  0
payment_installments:  0
payment_value:  0

In [5]:
dc['payment_type'].value_counts(dropna=False)

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [8]:
dc['payment_type']=dc['payment_type'].str.replace('_', ' ') 
dc['payment_type'].value_counts(dropna=False)

payment_type
credit card    76795
boleto         19784
voucher         5775
debit card      1529
not defined        3
Name: count, dtype: int64

In [12]:
dc['payment_value'].value_counts(dropna=False)

payment_value
50.00     324
20.00     274
100.00    255
77.57     250
35.00     165
         ...
153.87      1
356.53      1
205.71      1
100.55      1
363.31      1
Name: count, Length: 29077, dtype: int64

In [14]:
dc.info()
dc.tail()

<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB

,order_id,payment_sequential,payment_type,payment_installments,payment_value
103881,0406037ad97740d563a178ecc7a2075c,1,boleto,1,363.31
103882,7b905861d7c825891d6347454ea7863f,1,credit card,2,96.80
103883,32609bbb3dd69b3c066a6860554a77bf,1,credit card,1,47.77
103884,b8b61059626efa996a60be9bb9320e10,1,credit card,5,369.54
103885,28bbae6599b09d39ca406b747b6632b1,1,boleto,1,191.58

In [15]:
dc.to_csv('clean_dataset/order_payments_cleaned.csv', index=False, encoding='utf-8')