In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dc = pd.read_csv('raw_dataset/olist_sellers_dataset.csv') 
dc.info() 
dc.head()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [3]:
dc.columns.is_unique #Check data duplikat di setiap kolom (output: True)

True

In [4]:
#Check jumlah missing value di setiap kolom  
print('seller_id: ', dc['seller_id'].isna().sum())
print('seller_zip_code_prefix: ', dc['seller_zip_code_prefix'].isna().sum())
print('seller_city: ', dc['seller_city'].isna().sum())
print('seller_state: ', dc['seller_state'].isna().sum())

seller_id:  0
seller_zip_code_prefix:  0
seller_city:  0
seller_state:  0

In [9]:
state_mapping = {
    'AC': 'Acre',
    'AL': 'Alagoas',
    'AM': 'Amazonas',
    'AP': 'Aapá',
    'BA': 'Bahia',
    'CE': 'Ceará',
    'DF': 'Distrito Federal',
    'ES': 'Espírito Santo',
    'GO': 'Goiás',
    'MA': 'Maranhão',
    'MG': 'Minas Gerais',
    'MS': 'Mato Grosso do Sul',
    'MT': 'Mato Grosso',
    'PA': 'Pará',
    'PB': 'Paraíba',
    'PE': 'Pernambuco',
    'PI': 'Piauí',
    'PR': 'Paraná',
    'RJ': 'Rio de Janeiro',
    'RN': 'Rio Grande do Norte',
    'RO': 'Rondônia',
    'RR': 'Roraima',
    'RS': 'Rio Grande do Sul',
    'SC': 'Santa Catarina',
    'SE': 'Sergipe',
    'SP': 'São Paulo',
    'TO': 'Tocantins'
}
dc['seller_state']=dc['seller_state'].map(state_mapping) 
dc['seller_state'].value_counts(dropna=False)

seller_state
São Paulo              1849
Paraná                  349
Minas Gerais            244
Santa Catarina          190
Rio de Janeiro          171
Rio Grande do Sul       129
Goiás                    40
Distrito Federal         30
Espírito Santo           23
Bahia                    19
Ceará                    13
Pernambuco                9
Paraíba                   6
Rio Grande do Norte       5
Mato Grosso do Sul        5
Mato Grosso               4
Rondônia                  2
Sergipe                   2
Acre                      1
Piauí                     1
Maranhão                  1
Amazonas                  1
Pará                      1
Name: count, dtype: int64

In [11]:
dc.info()
dc.tail()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB

,seller_id,seller_zip_code_prefix,seller_city,seller_state
3090,98dddbc4601dd4443ca174359b237166,87111,sarandi,Paraná
3091,f8201cab383e484733266d1906e2fdfa,88137,palhoca,Santa Catarina
3092,74871d19219c7d518d0090283e03c137,4650,sao paulo,São Paulo
3093,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,Rio Grande do Sul
3094,9e25199f6ef7e7c347120ff175652c3b,12051,taubate,São Paulo

In [12]:
dc.to_csv('clean_dataset/sellers_cleaned.csv', index=False, encoding='utf-8')